apiVersion: apps/v1
kind: Deployment
metadata:
  name: pathagar-ui
  labels:
    app: pathagar

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pathagar-ui
  template:
    metadata:
      labels:
        app: pathagar-ui
    spec:
      containers:
        - name: pathagar-ui
          image: eu.gcr.io/marufh/pathagar-ui:v43
          ports:
            - containerPort: 80
